[package]
name = "jp_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = {version = "*", optional = true}

[dev-dependencies]
test-case = "*"

[features]
default = []
hiragana = []
furigana = ["itertools"]
