[package]
name = "jp_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = {version = "*", optional = true}

[dev-dependencies]
test-case = "*"
criterion = "0.4.0"
rand = "0.8.5"

[features]
default = ["furigana"]
hiragana = []
furigana = ["itertools"]

 [[bench]]
name = "my_bench"
harness = false
